server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  instance:
    appname: com.fg.eureka
logging:
  level:
    com:
     netflix:
       eureka: off
       discovery: off
spring:
  security:
    user:
      name: admin
      password: admin